### ISSUE TITLE
module name

### ISSUE THREAD

**Issue by tst2005** [love2d-community/love-api#12]
Hello,

I suggest to use uniq module names, something like `require "api.love"`.
It should help to defined other API like the lua one (in `api.lua`).

See https://github.com/tst2005/love-api/tree/modnames

Regards,

**Comment by rm-code** [comment]
Hey @tst2005,

I am not sure I understand the possible benefits of this.
> It should help to defined other API like the lua one (in api.lua).

What do you mean here?

Best wishes
Robert
