### ISSUE TITLE
Update css for quick reference

### ISSUE THREAD

**Issue by rm-code** [love2d-community/love-api#36]
@hahawoo I thought about maybe changing / updating the css styling for the quick-reference. I like the colors of the https://love2d.org/ main page.

**Comment by hahawoo** [comment]
Go for it! :)

**Comment by hahawoo** [comment]
Trying out a new style: http://love2d-community.github.io/love-api/test/

**Comment by daviel** [comment]
Is this fixed with #62 ?

**Comment by rm-code** [comment]
indeed it is 👍
