### ISSUE TITLE
Quick references for older versions

### ISSUE THREAD

**Issue by hahawoo** [love2d-community/love-api#37]
Each release could have its own reference, for people using older versions.

For example: http://love2d-community.github.io/love-api/0.9.2/

http://love2d-community.github.io/love-api/ could still be for the latest version.

**Comment by rm-code** [comment]
Sounds good!

**Comment by hahawoo** [comment]
I've added:
http://love2d-community.github.io/love-api/0.9.1/
http://love2d-community.github.io/love-api/0.9.2/
http://love2d-community.github.io/love-api/0.10.0/
http://love2d-community.github.io/love-api/0.10.1/
http://love2d-community.github.io/love-api/0.10.2/
