### ISSUE TITLE
Embed CSS into HTML 

### ISSUE THREAD

**Issue by karai17** [love2d-community/love-api#41]
While generally not considered best practice, I think sticking the CSS into a `<style>` tag would be good for this. It would allow people to download the whole API reference, styled, in a single file.

Also maybe bump the font size up a bit? it's pretty small~

**Comment by rm-code** [comment]
Hm we could update the generator code to copy the css file into the html file?

**Comment by karai17** [comment]
Is the generator available?

**Comment by rm-code** [comment]
Yes, you can find it here: 
https://github.com/love2d-community/love-api/blob/gh-pages/generator/html-generator.lua

Would you be up for a PR? Not sure when I'll have time to do it.

**Comment by karai17** [comment]
I can poke it later today, yeah.

**Comment by karai17** [comment]
PR #42 at your service!
