### ISSUE TITLE
Adding love-api-to-ldt-luadoc to README

### ISSUE THREAD

**Issue by hahawoo** [love2d-community/love-api#48]
[love-api-to-ldt-luadoc](https://github.com/leafi/love-api-to-ldt-luadoc) uses love-api and seems like it should go in the projects list.

**Comment by hahawoo** [comment]
Also [love-ide](https://github.com/rameshvarun/love-ide) (used [here](https://github.com/rameshvarun/love-ide-data)).

**Comment by rm-code** [comment]
Sounds good to me :)

**Comment by hahawoo** [comment]
Done!
