### ISSUE TITLE
0.11.0 Update

### ISSUE THREAD

**Issue by rm-code** [love2d-community/love-api#54]
Started a branch at https://github.com/love2d-community/love-api/tree/update_to_love0110

TODO:

- [x] love.data.decompress
- [x] love.filesystem.getCRequirePath
- [x] love.filesystem.setCRequirePath
- [x] Image:replacePixels
- [x] Channel:demand
- [x] Channel:supply
- [x] World:update
- [x] love.data.decode
- [x] love.data.encode
- [x] love.data
- [x] RecordingDevice
- [x] Texture:getMipmapCount
- [x] Texture
- [x] Texture:getTextureType
- [x] Texture:getDepth
- [x] Texture:getLayerCount
- [x] Texture:getFormat
- [x] Texture:isReadable
- [x] love.graphics.applyTransform
- [x] love.graphics.replaceTransform
- [x] love.graphics.getFrontFaceWinding‎
- [x] love.graphics.setFrontFaceWinding‎
- [x] love.data.hash
- [x] HashFunction
- [x] ContainerType
- [x] love.math.newTransform‎
- [ ] PixelFormat
- [x] love.graphics.transformPoint
- [x] love.graphics.inverseTransformPoint
- [x] love.graphics.setMeshCullMode
- [x] love.graphics.getMeshCullMode
- [x] love.graphics.getDepthMode
- [x] love.graphics.setDepthMode
- [ ] SpriteBatch:addLayer
- [ ] SpriteBatch:set
- [ ] SpriteBatch:setLayer
- [ ] Body:isTouching
- [ ] ParticleSystem:setEmissionArea‎
- [ ] ParticleSystem:getEmissionArea‎
- [ ] Texture:getPixelWidth‎
- [ ] Canvas:newImageData
- [ ] Texture:getPixelHeight‎
- [ ] Texture:getPixelDimensions‎
- [ ] Texture:getFormat
- [ ] Texture:getFilter‎
- [ ] Texture:setFilter‎
- [ ] love.graphics.getPixelWidth‎
- [ ] love.graphics.getPixelHeight
- [ ] love.graphics.getPixelDimensions
- [ ] Texture‎
- [ ] CompressedImageFormat‎
- [ ] TextureType
- [ ] love.data.compress‎
- [ ] love.data.decompress‎
- [ ] Source:tell‎
- [ ] Source:seek
- [ ] Source:getDuration
- [ ] love.physics.newRopeJoint‎
- [ ] Transform:reset‎
- [ ] Transform:clone
- [ ] Transform:setTransformation
- [ ] Transform:reset
- [ ] Transform
- [ ] Transform:transformPoint‎
- [ ] Transform:inverseTransformPoint‎
- [ ] Transform:translate
- [ ] Transform:rotate
- [ ] Transform:scale
- [ ] Transform:shear
- [ ] Transform:apply
- [ ] Transform:getMatrix
- [ ] Transform:setMatrix

**Comment by rm-code** [comment]
@hahawoo Any idea how we could add this:
https://love2d.org/wiki/PixelFormat

?

**Comment by Positive07** [comment]
The time has come! The wiki is not yet up to date, but by updating love-api we can help with that effort too. I'll be trying to get a few PRs in into that new branch

**Comment by rm-code** [comment]
Are there any wiki pages which use the PixelFormats directly? After a quick search I only found it in `love.graphics.getImageFormats` as `table formats` and that's exactly how I'd handle it:

```
returns = {
	{
		type = 'table',
		name = 'formats',
		description = 'A table containing PixelFormats as keys, and a boolean indicating whether the format is supported as values. Not all systems support all formats.'
	},
	...
}
```

My question was aiming at the problem, that the enum page itself has multiple sections and a data table for the description of the constants.

**Comment by Positive07** [comment]
The functions that return it as a table are:
- `love.graphics.getCanvasFormats` (The wiki says that it returns CanvasFormats)
- `love.graphics.getImageFormats`

The function that return it as an enum are:
- `Texture:getFormat`
- `ImageData:getFormat`
- `CompressedImageData:getFormat` (The wiki says that it returns a CompressedImageFormat)

The functions that take it as an enum parameter are:
- `love.graphics.newCanvas` (In the settings table)
- `love.graphics.newImageData` (Not documented in the wiki but basically `newImageData(w, h, format)`)

**Comment by Positive07** [comment]
So the table is split in three:
1- TextureFormat, mostly used for `newCanvas` and `Texture:getFormat`, only four of these can be used in `newImageData`
2- DepthFormats, used only for `newCanvas` and it's corresponding `getFormat` when working with depth buffers
3- CompressedFormats, used only for `CompressedImageData:getFormat`

One cannot make assumptions about what `getImageFormats` and `getCanvasFormats` can return, the safest would be to assume that any of the PixelFormats can be returned by them.

And even though the table is split like I detailed above, it would be best to just unify them for all the cases instead of having it split

**Comment by hahawoo** [comment]
I've updated it to 11.2 (via wiki scraping, see #84). The PixelFormat information still isn't there though.

**Comment by rm-code** [comment]
@hahawoo If you want to, we can close this issue.

**Comment by pablomayobre** [comment]
I'd argue that this should be closed and a new one should be opened with what's currently missing

I'll probably open one for the 11.3 N/A release that will come at some point, since there are already wiki entries for some of it and the changelog was recently updated in the main repo.

**Comment by hahawoo** [comment]
@rm-code @pablomayobre Sounds good!
