### ISSUE TITLE
Add test to make sure there is a variants table

### ISSUE THREAD

**Issue by rm-code** [love2d-community/love-api#67]
For example `love.window.restore` caused some issues for love-atom, because the empty variants table was omitted.

```
        {
            name = 'restore',
            description = 'Restores the size and position of the window if it was minimized or maximized.',
            variants = {
                {}
            }
        },
```

@Positive07 Maybe you have some time to take a look at this? :)

**Comment by Positive07** [comment]
Would it be a good idea to just do #45 and make a simple test thingy that loops over what needs to be there?
