### ISSUE TITLE
No Data/love.data module.

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d-community/love-api#70]
https://github.com/love2d-community/love-api/blob/0a4a337c4dd16e64201cc49c11ec3ca8e5f816bb/love_api.lua#L68L86

**Comment by rm-code** [comment]
It just needs to be required. If you are up for a pull request, I'll gladly merge it.

Otherwise I'll add it later on

**Comment by rm-code** [comment]
Should be available now.
