### ISSUE TITLE
Missing Transform variant of love.graphics.draw

### ISSUE THREAD

**Issue by MikuAuahDark** [love2d-community/love-api#75]
[love.graphics.draw](https://love2d.org/wiki/love.graphics.draw) accepts [Transform](https://love2d.org/wiki/Transform) as 2nd (for Drawable) or 3rd (for Texture+Quad) argument since LOVE 11.0.

**Comment by Positive07** [comment]
I still didn't get to `love.graphics` but I'll check this out once I get there! Thanks 😃
