### ISSUE TITLE
Version discrepancy (is 11.3 or 11.2 the latest version supported?)

### ISSUE THREAD

**Issue by tobiasvl** [love2d-community/love-api#88]
The table's `latest` version is displayed in the upper left corner as 11.2.

The badge in the README file in this repo says 11.3.

[The table structure example in the README](https://github.com/love2d-community/love-api#table-structure) says 11.2

Is this table updated for 11.3 or not? Kinda hard to tell.

**Comment by hahawoo** [comment]
Good point, I've updated the README table structures to show 11.3. I'm confused about the `latest` version in the upper left corner though, the upper left corner of what exactly? The latest "release" is 0.10.0, because no one has made any releases since then.

**Comment by MikuAuahDark** [comment]
The pages is now generated using GitHub Actions as of b913d6e804402d39401b343e3032b30eef0c83bb.
