### ISSUE TITLE
Is love.font docs missing completly?

### ISSUE THREAD

**Issue by IS2511** [love2d-community/love-api#90]
Is this on purpose? I think it's missing by mistake... Fix?

**Comment by hahawoo** [comment]
I left `love.font` out of the HTML generator because, as far as I knew at the time, these functions were used internally in LOVE's code but there wasn't a reason for a LOVE user to use them instead of `love.graphics.newFont` or `love.graphics.newImageFont`, but please let me know if I was mistaken!

**Comment by IS2511** [comment]
There are some new things in `love.font`, like strict "newFont" functions, class `GlyphData` and a few enums. Worth the inclusion?

**Comment by MikuAuahDark** [comment]
With #89, `love.font` documentation is now available as JSON file, but it left disabled in the generated HTML.

**Comment by MikuAuahDark** [comment]
Fixed in f4ff3e0d0846f6ab41d4e722375ffc24a31df362 and now the pages is automatically updated with GitHub Actions.
